SET 'auto.offset.reset' = 'earliest';
SET 'enable.auto.commit' = 'true';
SET 'auto.commit.interval.ms' = '1000';

CREATE STREAM TRIPS ("payload" MAP < VARCHAR, VARCHAR >) WITH (KAFKA_TOPIC = 'postgres-trips', VALUE_FORMAT = 'JSON');
CREATE STREAM TRIPS_SOURCE WITH (PARTITIONS=1) AS SELECT "payload"['id'] as ID, "payload"['user_id'] as USER_ID, "payload"['start_station'] as START_STATION, "payload"['start_time'] as START_TIME, "payload"['end_station'] as END_STATION, "payload"['end_time'] as END_TIME from TRIPS;
CREATE STREAM TRIPS_PARTITION_BY_JOURNEY WITH (PARTITIONS=1) AS SELECT ID, USER_ID, CAST(END_TIME AS INT) - CAST(START_TIME AS INT) as TRIP_TIME, START_STATION + '-' + END_STATION AS JOURNEY FROM TRIPS_SOURCE WHERE END_TIME IS NOT NULL PARTITION BY JOURNEY;
CREATE TABLE TRIPS_AVERAGE_TIME WITH (VALUE_FORMAT = 'AVRO') AS SELECT JOURNEY, AVG(TRIP_TIME) as TRIP_AVG_TIME FROM TRIPS_PARTITION_BY_JOURNEY GROUP BY JOURNEY;
